AEA-3787 Add target identity options to Proxygen
NHSDigital/proxygen-api-specification pull request #18
Opened 2024-02-23 11:16 UTC by originalphil

## Summary
* :sparkles: New Feature

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2024-02-28 16:13 UTC, acarriedev requested changes

2024-02-28 16:13 UTC, acarriedev commented on specification/proxygen.yaml
> +    If a header named `NHSD-Session-URID` (the default `urid-header-name`) is present in the request, it will flow through to the backend as that defined in your specification.
This is good. I think we just need to be slightly clearer that the headers will always be NHSD-Session-URID and NHSD-Session-UUID in the request from the consumer to the proxy and the headers specified are the headers the proxy will send the values to the back in.

2024-02-28 16:13 UTC, acarriedev commented on specification/proxygen.yaml
> +        uuid-header-name: "nhsd-identity-uuid"
I think use the capitals here as they are on the defaults.

2024-02-28 17:12 UTC, originalphil commented on specification/proxygen.yaml
> +    If a header named `NHSD-Session-URID` (the default `urid-header-name`) is present in the request, it will flow through to the backend as that defined in your specification.
Reworded this.

2024-02-28 17:14 UTC, originalphil commented on specification/proxygen.yaml
> +        uuid-header-name: "nhsd-identity-uuid"
I didn't intend for one of these to be the same as the default, only in lowercase. I've made them more 'custom' rather than capitalise and make it more similar to the defaults. I think that would be confusing.

2024-02-29 11:44 UTC, acarriedev approved these changes

2024-02-29 11:44 UTC, merged