APM-4483 MTLS changes
NHSDigital/proxygen-api-specification pull request #8
Opened 2023-08-15 12:29 UTC by acarriedev

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2023-08-15 14:58 UTC, acarriedev commented on specification/proxygen.yaml
> +      $ref: https://proxygen.prod.api.platform.nhs.uk/components/securitySchemes/nhs-login-p0
Changed all of these as they should be more stable/reliable in theory that ptl

2023-08-23 12:33 UTC, tonyheap requested changes

2023-08-23 12:33 UTC, tonyheap commented on specification/proxygen.yaml
> +    This [extension to the OpenAPI specification](https://swagger.io/docs/specification/openapi-extensions/) is read during API Instance deployment and controls functionality specific to the API Plat
lower case "I" on "instance"?

2023-08-23 12:33 UTC, tonyheap commented on specification/proxygen.yaml
> +    #### Target Specification
lower case S

2023-08-23 12:33 UTC, tonyheap commented on specification/proxygen.yaml
> +    ##### External Target
Lower case T

2023-08-23 12:33 UTC, tonyheap commented on specification/proxygen.yaml
> +    ###### mTLS Security
Lower case S

2023-08-23 12:33 UTC, tonyheap commented on specification/proxygen.yaml
> +    ###### API Key external target
lower case K - here and below

2023-08-23 12:40 UTC, tonyheap commented on specification/proxygen.yaml
> +    #### Rate Limiting
lower case L

2023-08-23 12:40 UTC, tonyheap commented on specification/proxygen.yaml
> +    #### API Products
lower case P

2023-08-24 07:36 UTC, merged